# Generated by Django 5.0.7 on 2024-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
