# Generated by Django 5.0.7 on 2024-07-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0002_alter_testuser_email_alter_testuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='filename',
            field=models.CharField(default='default_filename.webp', max_length=255),
        ),
    ]
